### ISSUE TITLE
How to use uplaydll

### ISSUE THREAD

**Issue by kacper-serewis** [claabs/ubisoft-demux-node#1]
Is there any way to communicate with `(service_)uplaydll`?

I've added uplaydll as service in some files but I'm getting the following error:

```
if (!connectionId) throw new Error(`Failed to establish connection for ${serviceName}`);
```

So I guess it's not possible the way I want to do it.

**Comment by claabs** [comment]
I've only been able to obtain the service names by capturing packets in Wireshark. I haven't seen one for UplayDll, but it might not be that hard to guess. The services are defined here: https://github.com/claabs/ubisoft-demux-node/blob/master/src/proto-defs.ts#L13-L36

[This repo](https://github.com/claabs/ubisoft-dmx-decode) documents my strategy used to capture the Ubisoft Connect packets.

**Comment by kacper-serewis** [comment]
Thanks, will try to intercept UplayDll packets using your strategy!
